apiVersion: batch/v1
kind: Job
metadata:
  name: manual-minio-init
  namespace: kserve
spec:
  template:
    spec:
      containers:
      - name: create-bucket
        image: minio/mc:latest
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: my-minio-secret
              key: AWS_ACCESS_KEY_ID
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-minio-secret
              key: AWS_SECRET_ACCESS_KEY
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "1. Configuring MinIO Client..."
          # We use the internal DNS name: minio-service
          mc alias set myminio http://minio-service:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD
          
          echo "2. Creating Bucket..."
          mc mb myminio/mlflow --ignore-existing
          
          echo "3. Listing Buckets to verify..."
          mc ls myminio
      restartPolicy: Never